/* Generated from external program, do not modify */
#ifndef INCLUDE_NTGEN_NTERM_H_
#define INCLUDE_NTGEN_NTERM_H_
#define PROGRAM 1
#define DECLR_LIST 2
#define FUNC_DECLR 3
#define VAR_DECLR 4
#define DECLR 5
#define RET_TYPE 6
#define INIT_PREFIX 7
#define INTIALIZER_LIST 8
#define ARRAY_INTIALIZER 9
#define INTIALIZER 10
#define ID_DECLR_LIST 11
#define ID_DECLR 12
#define VAR_DECLR_LIST 13
#define PARAM_LIST 14
#define PARAM 15
#define BLOCK 16
#define STMT_LIST 17
#define STMT 18
#define RETURN_VAL 19
#define WHILE_STMT 20
#define FOR_STMT_RANGE 21
#define FOR_STMT_UNTIL_RANGE 22
#define IF_STMT 23
#define ELSE_IF_LIST 24
#define ELSE_IF_STMT 25
#define ELSE_STMT 26
#define ARG_LIST 27
#define ARG 28
#define LITERAL 29
#define EXPR 30
#define ASSIGN_EXPR 31
#define FUNC_CALL 32
#define BOOL_EXPR 33
#define QUEST 34
#define SIMPLE_TYPE 35
#define NULLABLE_TYPE 36
#define ARRAY_TYPE 37
#define TYPE 38
#define ARITH_EXPR 39
#define CAST_EXPR 40
#define ELVIS_EXPR 41
#define UNARY_EXPR 42
#define NULL_ASSERT 43
#define POSTFIX_EXPR 44
#define PRIMARY_EXPR  45
#define ARRAY_SUBSCRIPT 46
#define METHOD_CALL 47
#define SAFE_METHOD_CALL 48
#endif  // INCLUDE_NTGEN_NTERM_H_