from os import close
import re
from sys import stdout
from typing import TextIO


def get_file_lines(filename: str) -> list[str]:
    """Get all the lines of a file"""
    with open(filename, "r") as file:
        lines = file.readlines()
    return lines


def collect_lines(lines: list[str]) -> str:
    """Collect lines into one string"""
    sb = ""
    for line in lines:
        sb += line
    return sb


def get_terminal_names(file_content: str) -> list[str]:
    """
    Helper function that finds all the non-terminals
    This is accomplished by using a regex to find all the non-terminals
    resulting from each product rule in the bison file.
    """
    matches = re.findall(r"\n+[a-z_]+\s*:\s*", file_content)
    sanitized_matches = []
    for match in matches:
        sanitized_match = str(match).strip("\n")
        idx = sanitized_match.find(":")
        sanitized_match = sanitized_match[:idx].strip(" ")
        sanitized_matches.append(sanitized_match)
    return sanitized_matches


def write_table(
    input_filename: str,
    output_stream: TextIO,
    start_id: int = 1,
    sep_filename: str | None = None,
):
    """
    Creates a table of non-terminal names that can be queried using it's corresponding ID:
        `NTERM_TABLE[nterm_id - NTERM_ID_START]`, where nterm_id is some id generated by ntgen.
    """
    nterms = get_terminal_names(collect_lines(get_file_lines(input_filename)))
    max_nterm_size = len(max(nterms, key=len)) + 1  # inc to account for null-term
    output_stream.write(f"#define NTERM_TABLE_SIZE {len(nterms)}\n")
    output_stream.write(f"#define NTERM_MAX_LEN {max_nterm_size}\n")
    output_stream.write(f"#define NTERM_ID_START {start_id}\n")
    if sep_filename != None:
        output_stream.write(f"extern const char* NTERM_TABLE[];")
        sep_output_stream = open(sep_filename, "w")
        sep_output_stream.write("const char *NTERM_TABLE[NTERM_TABLE_SIZE] = {\n")
        for nterm in nterms[:-1]:
            sep_output_stream.write(f'\t"{nterm}",\n')
        sep_output_stream.write(f'\t"{nterms[-1]}"\n')
        sep_output_stream.write("};\n")
    else:
        output_stream.write("static char *NTERM_TABLE[NTERM_TABLE_SIZE] = {\n")
        for nterm in nterms[:-1]:
            output_stream.write(f'\t"{nterm}",\n')
        output_stream.write(f'\t"{nterms[-1]}"\n')
        output_stream.write("};\n")


def ntgen(
    input_filename: str,
    output_filename: str | None = None,
    start_id: int = 1,
    gen_table: bool = False,
    sep_filename: str | None = None,
):
    """Main function -- writes all the IDs to output stream"""
    # first id is the start id, get inc after
    id: int = start_id
    nterms = get_terminal_names(collect_lines(get_file_lines(input_filename)))
    # construct filestream
    output_stream = stdout if output_filename == None else open(output_filename, "w")
    output_stream.write("/* Generated from external program, do not modify */\n")
    header = (
        f"INCLUDE_{output_filename.removesuffix('.h').upper()}_H_"
        if output_filename != None
        else "INCLUDE_NTGEN_NTERM_H_"
    )
    output_stream.write(f"#ifndef {header}\n")
    output_stream.write(f"#define {header}\n")
    for nterm in nterms:
        output_stream.write(f"#define {nterm.upper()} {id}\n")
        id += 1
    if gen_table == True:
        write_table(input_filename, output_stream, start_id, sep_filename)
    output_stream.write("#endif  // INCLUDE_NTGEN_NTERM_H_\n")
